global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']
    
  - job_name: 'manager-api'
    static_configs:
      - targets: ['172.30.140.142:8001']
    
  - job_name: 'vllm-dgx-01'
    static_configs:
      - targets: ['dgx-01:8000']
    
  - job_name: 'vllm-local'
    static_configs:
      - targets: ['172.30.140.142:8000']
